### ISSUE TITLE
`parse': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by bronzdoc** [duckinator/inq#287]
When I try to get a report from `rubymem.com` i'm getting the following error

```shell
$ inq --verbose --repository rubymem/rubymem.com --date 2020-01-01
```

```
Fetching rubymem/rubymem.com commit data....
Fetching rubymem/rubymem.com issue data..
Fetching rubymem/rubymem.com pull request data..
Fetching Travis CI branch data.
Fetching Travis CI build data.
Traceback (most recent call last):
        23: from /Users/bronzdoc/.rbenv/versions/2.6.3/bin/inq:23:in `<main>'
        22: from /Users/bronzdoc/.rbenv/versions/2.6.3/bin/inq:23:in `load'
        21: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/exe/inq:7:in `<top (required)>'
        20: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/exe.rb:19:in `run'
        19: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/exe.rb:58:in `execute'
        18: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/exe.rb:46:in `save_reports'
        17: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:106:in `save_all'
        16: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:71:in `to_h'
        15: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:71:in `map'
        14: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:75:in `block in to_h'
        13: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:75:in `map'
        12: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:75:in `each'
        11: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report_collection.rb:94:in `block (2 levels) in to_h'
        10: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report.rb:76:in `to_html'
         9: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report.rb:65:in `to_h'
         8: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/report.rb:137:in `report_hash'
         7: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:49:in `builds'
         6: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/cacheable.rb:18:in `cached'
         5: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:51:in `block in builds'
         4: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:51:in `map'
         3: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:117:in `normalize_build'
         2: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:117:in `each'
         1: from /Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:119:in `block in normalize_build'
/Users/bronzdoc/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/inq-31.0.0/lib/inq/sources/ci/travis.rb:119:in `parse': no implicit conversion of nil into String (TypeError)
```

**Comment by duckinator** [comment]
https://github.com/duckinator/inq/blob/master/lib/inq/sources/ci/travis.rb#L118

Looks like `next if k.nil?` should be `next if k.nil? || result[k].nil?`
